### ISSUE TITLE
Does the official plan to provide more ways of self-hosting, such as Docker

### ISSUE THREAD

**Issue by Plus-L** [lunary-ai/lunary#118]
Hi! I am very interested in lunary. I would like to ask if there are any official plans to provide more self-hosting ways?

**Comment by vincelwt** [comment]
Hi! Big update coming in < 2 weeks :)

**Comment by hughcrt** [comment]
Hi@ @Plus-L,
You can find our self-hosting plan here: https://lunary.ai/pricing/self-hosted.
You should find everything in the main repo to spin up a dev environment. Please let use know if you can't make it work on your own.
