### ISSUE TITLE
LunaryModule not found - Langchain

### ISSUE THREAD

**Issue by SantoshKumarRavi** [lunary-ai/lunary#119]
i followed this below doc for integrating in langchain 

https://lunary.ai/docs/langchain

import { LunaryHandler } from 'langchain/callbacks/handlers/lunary';

error is showing in my typescript file
`Cannot find module 'langchain/callbacks/handlers/lunary'
`

Tried with js too

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './callbacks/handlers/lunary' is not defined by "exports" in D:\chatGPT-Max-Prototype\node_modules\langchain\package.json imported from D:\chatGPT-Max-Prototype\index.js
`

how to import  LunaryHandler  in my app ?

**Comment by SantoshKumarRavi** [comment]
i tried alias too.

import { LLMonitorHandler as LunaryHandler } from 'langchain/callbacks/handlers/llmonitor';

but it does not show "appId " attribute in LunaryHandler class.
which langchain version suited for this ?

**Comment by vincelwt** [comment]
Hi @SantoshKumarRavi 
Sorry about that, we're still waiting on Langchain to merge the PR with the name update. We should have waited before updating the docs and will revert in the meantime.

The alias like you did should work. Might be a typescript error, otherwise does setting `LLMONITOR_APP_ID` as an env variable work ?

**Comment by SantoshKumarRavi** [comment]
thanks for the quick reply @vincelwt 

I got llmonitor not found error, and i installed manually with npm. now this error gone.


```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'llmonitor' imported from D:\chatGPT-Max-Prototype\node_modules\@langchain\community\dist\callbacks\handlers\llmonitor.js
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
```

**Comment by SantoshKumarRavi** [comment]
i will check with each user analytics

**Comment by SantoshKumarRavi** [comment]
i am able to  see my user usage in dash board . is there any api for that like if i pass userID, i will get those user result ?

**Comment by vincelwt** [comment]
Hi! Sorry for the delay.
The correct way to import for langchain now is like this with the latest version of the `lunary` nom module:
```
import { LunaryHandler } from "lunary/langchain"
```

We currently don't have an ability to filter by user id directly in the API but it's coming very soon! Thanks
