### ISSUE TITLE
Sorry to be that guy... *types*?

### ISSUE THREAD

**Issue by nathan-chappell** [lunary-ai/lunary#121]
Is there any interest in adding types to the module?  I'm looking for something to replace helicone, and so far this is the only thing that I've found that I like (I don't trust langchain to make langsmith, but their features in relation to dataset building look quite interesting to me).  I'd say one thing that stops me from jumping right in is the lack of type annotations.  I'm not asking you guys to do them, I'm asking if it's even something you guys would be interested in having.  I'm not sure how hard it would be (though I'd be willing to take a crack at it at some point), mostly because I haven't played around too much with the opentelemetry stuff (and really don't want to).

But the lightweight straightforward adaptation of opentelementry to the OpenAI use case is exactly what I want and seems like you guys have pretty much implemented, so great.

**Comment by hughcrt** [comment]
Hi @nathan-chappell,
You’re talking about python right?
If this is the case, we definitely plan to add them.

**Comment by nathan-chappell** [comment]
@hughcrt yes `python`, and glad to hear it!  I'll probably start using you guys once I have an opportunity to switch over.
