### ISSUE TITLE
Should't this be DATABASE_URL?

### ISSUE THREAD

**Issue by playermanny2** [lunary-ai/lunary#123]
Hi -- working on deploying locally using bun dev and running into issues that i'm unwraveling...

https://github.com/lunary-ai/lunary/blob/c5aa97e5113f90f1bfe7c1eb7a741de2c2a917c1/.env.example#L2

should this be DATABASE_URL to align to [packages/backend/utils/db.ts](https://github.com/lunary-ai/lunary/blob/c5aa97e5113f90f1bfe7c1eb7a741de2c2a917c1/packages/backend/utils/db.ts#L5)

I noticed, you'd also need to set env var
`NEXT_PUBLIC_API_URL="http://localhost:3333"`

**Comment by vincelwt** [comment]
Hi! Sorry about that, you're right :) I've updated the .env.example file to reflect the proper variables.

**Comment by Swty13** [comment]
@playermanny2 @vincelwt 
Hello, I've executed the code using `npm run dev`. The connection has been successfully established as indicated below:
[1] ✅ Lunary API server is now listening on port 3333
[1] ✅ Database connection established.

What would be the subsequent action? How can I navigate to or monitor the Lunary UI?
