### ISSUE TITLE
Unable to create local deployment

### ISSUE THREAD

**Issue by clockfly** [lunary-ai/lunary#125]
1. Seems missing postgres init scripts in the repo.
2. After using some old postgres init script from 0.3,  it reports error when trying to login.
```
PostgresError: relation "account" does not exist
```
3. Need doc about how to setup the local user for local setup.

**Comment by vincelwt** [comment]
Hi! Thanks we'll update the repo very soon with the appropriate migration
@hughcrt

**Comment by hughcrt** [comment]
Hi, we’ve added init and migration script under packages/db. We’ll make sure to keep those up to date in the future.
