### ISSUE TITLE
Server-side error with vercel 'ai' npm package

### ISSUE THREAD

**Issue by gardner** [lunary-ai/lunary#126]
Hi there,
  just reporting this in case it's an easy fix. It looks like vercel's `ai` npm package wraps things up in a weird way that isn't compatible with Lunary. 

This can be reproduced by cloning the [ai-chatbot](https://github.com/vercel/ai-chatbot) and wrapping the openai call with `monitorOpenAI` in `./app/api/chat/route.ts`

```
./app/api/chat/route.ts:40:31
20:50:29.356 | Type error: Argument of type 'ChatCompletion' is not assignable to parameter of type 'Response \| AsyncIterableOpenAIStreamReturnTypes'.
20:50:29.357 |  
20:50:29.357 | 38 \|   })
20:50:29.357 | 39 \|
20:50:29.357 | > 40 \|   const stream = OpenAIStream(res, {
20:50:29.357 | \|                               ^
20:50:29.357 | 41 \|     async onCompletion(completion) {
20:50:29.357 | 42 \|       const title = json.messages[1].content.substring(0, 100)
20:50:29.358 | 43 \|       const id = json.id ?? nanoid()
20:50:29.409 | ELIFECYCLE  Command failed with exit code 1.
20:50:29.436 | Error: Command "pnpm run build" exited with 1
20:50:29.916
```

**Comment by hughcrt** [comment]
Hi,

We need to update our SDK and examples to explain how to make it work with Next.js. 
In the meantine, here is an example that works well with Next.js App router and Lunary:

```typescript
lunary.init({ appId: "..." });
const openai = new OpenAI({
  apiKey: "sk-...",
});

monitorOpenAI(openai);
export const runtime = "edge";

export async function GET() {
  const result = await openai.chat.completions.create({
    model: "gpt-3.5-turbo",
    temperature: 0.9,
    stream: true,
    messages: [
      { role: "system", content: "You are an helpful assistant" },
      { role: "user", content: "Print a random string" },
    ],
  });

  const stream = iteratorToStream(result);
  return new Response(stream);
}


function iteratorToStream(iterator: any) {
  const encoder = new TextEncoder();
  return new ReadableStream({
    async pull(controller) {
      try {
        const { value, done } = await iterator.next();
        if (done) return controller.close();
        const bytes = encoder.encode(JSON.stringify(value) + "\n");
        controller.enqueue(bytes);
      } catch (error) {
        controller.error(error);
      }
    },
  });
}
```

**Comment by gardner** [comment]
As a workaround: 

It seems to work in spite of the type error. Adding `@ts-ignore` allows the build stage to pass and then the code operates as expected. e.g.

```
// @ts-ignore
const stream = OpenAIStream(res, {
  async onCompletion(completion) {

```

**Comment by BigStar-2024** [comment]
Hello, brothers.

**Comment by BigStar-2024** [comment]
I saw the "Add SMTP email sending to Node.js backend" task on UpWork.
And then I came to here to contribute to this.
What do you think?

**Comment by hughcrt** [comment]
Hi @BigStar-2024, yes you can

**Comment by BigStar-2024** [comment]
okay, Thanks for your response.
But first I think this chat is not good to have a realtime chat.
So I suggest following chat.
What do you think?
Telegram:  SkyTech_2024
Skype: BigStar2024

**Comment by 7HR4IZ3** [comment]
Regarding the types, everything seems to be working fine for me:

Although I did update the code to use the openai `openai.streaming.Stream` object's `tee` function if possible so the returned value of the `create` function is the same regardless of if you wrap `OpenAI` with `monitorOpenAI` or not.

I'll write some tests for it then submit a PR

**With Lunary and streaming**
![1001190614-01](https://github.com/lunary-ai/lunary/assets/90985774/5231e4f8-0138-4496-bd96-93245b4183a9)

**With Lunary and without streaming**
![1001190615-01](https://github.com/lunary-ai/lunary/assets/90985774/58e1ee86-ad6c-4e35-93ca-82eee9eb9f8a)

**Without Lunary but with streaming**
![1001190616-01](https://github.com/lunary-ai/lunary/assets/90985774/9fd85baf-3fc4-44f1-81fa-2634234c766b)

**Without Lunary and without streaming**
![1001190617-01](https://github.com/lunary-ai/lunary/assets/90985774/fd4c9c0c-c600-4afb-81fc-1321b85e6154)
