### ISSUE TITLE
getting started to run locally - errors with npm run dev

### ISSUE THREAD

**Issue by chauvinSimon** [lunary-ai/lunary#129]
Hi, I would really like to try Lunary locally!

Following the [readme section](https://github.com/lunary-ai/lunary?tab=readme-ov-file#running-locally), I have copied the `.env` and `npm install` worked well.

`npm run dev` raises these issues:

```
> lunary@1.0.0 dev
> concurrently "npm run frontend:dev" "npm run backend:dev"

[1] 
[1] > lunary@1.0.0 backend:dev
[1] > npm -w packages/backend run dev
[1] 
[0] 
[0] > lunary@1.0.0 frontend:dev
[0] > npm -w packages/frontend run dev
[0] 
[1] 
[1] > dev
[1] > tsx --env-file=.env --watch src/index.ts
[1] 
[0] 
[0] > dev
[0] > next dev -p 8080
[0] 
[1] node: .env: not found
[1] npm ERR! Lifecycle script `dev` failed with error: 
[1] npm ERR! Error: command failed 
[1] npm ERR!   in workspace: @lunary/backend 
[1] npm ERR!   at location: /home/simon-chauvin/drafts/lunary/packages/backend 
[1] npm run backend:dev exited with code 1
[0]    ▲ Next.js 14.1.0
[0]    - Local:        http://localhost:8080
[0] 
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v1/report","destination":"undefined/api/report"}
[0] 
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/report","destination":"undefined/api/report"}
[0] 
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v1/template","destination":"undefined/api/v1/template"}
[0] 
[0] 
[0] Error: Invalid rewrites found
[0] 
[0] npm run frontend:dev exited with code 0
```

- Coping `.env` to `packages/backend` helps for `[1] node: .env: not found`. 

- I do not understand why `destination` starts with `undefined/` in the error for the frontend: `destination does not start with ...`

- Whatsmore I am not sure what format I should give to `DATABASE_URL`. Something like `"postgresql://username:password@localhost:5432/mydatabase"`?

disclaimer: I have no experience with node, nor with Postgres.

**Comment by mdavidkeyrus** [comment]
Same for me

**Comment by edwardzjl** [comment]
@chauvinSimon Hi, I'm also trying to run Lunary locally, so the following might not be the best suggestions.

The `destination` variable is assigned [here](https://github.com/lunary-ai/lunary/blob/238dc7be6a2fc6b1a5d3d474cf624dad348021ab/packages/frontend/next.config.js#L32), [here](https://github.com/lunary-ai/lunary/blob/238dc7be6a2fc6b1a5d3d474cf624dad348021ab/packages/frontend/next.config.js#L36) and [here](https://github.com/lunary-ai/lunary/blob/238dc7be6a2fc6b1a5d3d474cf624dad348021ab/packages/frontend/next.config.js#L40), which should be set properly with `NEXT_PUBLIC_API_URL` environment variable. However the `.env` file is not picked when starting locally (I don't know why, I'm new in js. Maybe we need to install the [dotenv](https://github.com/motdotla/dotenv) as dev dependency). A dirty but quick fix is to export those env variables in your terminal before `npm run dev`

And yes, the `DATABASE_URL` should be something like `postgresql://username:password@localhost:5432/mydatabase`

Note that you need to initialize your database before starting the server. The init script can be found at `packages/db/init.sql`

**Comment by sanhal** [comment]
ya, set DATABASE_URL to  postgresql://username:password@localhost:5432/mydatabase

and do this 
`npm run dev --env=.env`

**Comment by sanjeevhalyal** [comment]
ya, set DATABASE_URL to postgresql://username:password@localhost:5432/mydatabase 

and run this `npm run dev --env=.env`

**Comment by HakaishinShwet** [comment]
i am getting same issue :-(( any perfect guide and fix for this?

**Comment by HakaishinShwet** [comment]
@hughcrt any progress on it?

**Comment by abhi-nav999** [comment]
@hughcrt any update?

**Comment by raviranjan0309** [comment]
@hughcrt - I am facing the same error. Can you post the fix for this or may be update the readme file?

TIA

**Comment by ancstefa-ps** [comment]
@hughcrt - I am getting the same error while trying to run locally. Any updates on this issue? Could you also please add the necessary steps in the read me file and what is the database url syntax that is expected to be used?

**Comment by HakaishinShwet** [comment]
@hughcrt ??

**Comment by hughcrt** [comment]
Hi everyone,
I'm truly sorry about the late answer. I'm writing a guide on how to run Lunary locally, and I will post it tomorrow.

**Comment by hughcrt** [comment]
You can find the instructions in `CONTRIBUTING.md` (https://github.com/lunary-ai/lunary/blob/fe47af01f06cfbcfe9504699522c414c3c745036/CONTRIBUTING.md)

Please let me know if you encounter any issues. I will respond promptly this time 😬

@HakaishinShwet @ancstefa-ps @raviranjan0309 @abhi-nav999 @edwardzjl @mdavidkeyrus @chauvinSimon

**Comment by tosilswc** [comment]
gave it a try and it starts! but now I have issues trying to log calls from LangChain. I invoke a chain doing

`import lunary

handler = lunary.LunaryCallbackHandler(app_id=os.environ.get('LUNARY_APP_ID'),api_url=os.environ.get('API_URL'),verbose=True)
config = RunnableConfig({"callbacks": [handler]})

and then mychain_output = mychain.invoke(randomstring,config=config)
`

but I get continuously a ERROR:root:[Lunary] Error sending events message on stdout.

I have set the env variables correctly I think (my project key for app_id and http://localhost:3333 for my api_url)
