### ISSUE TITLE
Confused about the Self-Hosted Community tier

### ISSUE THREAD

**Issue by eliorc** [lunary-ai/lunary#138]
On the website, I see a reference to a self-hosted Community version
![image](https://github.com/lunary-ai/lunary/assets/17727283/7055fae2-0d71-4a97-b479-3de2f0ecf265)

Me, as well as other organization like mine I believe, are interested in trying out Lunary without having data exit our eco-system, so we avoid going for the free Cloud tier. So I wanted to try out the self-hosted Community version.
When I click Open Repository and get to this repo - the docker folder is empty, and there is no information anywhere regarding how to self deploy the Community edition.

Am I missing something? Is there any documentation dedicated to explaining how to self host the Community version?

**Comment by hughcrt** [comment]
Hi @eliorc,
There's no Docker support for the community edition. We've provided instructions to run the project locally in `CONTRIBUTING.md`.
You can have access to the docker images or helm charts with paid plans.

**Comment by josh900** [comment]
Hi, I have spun it up myself, but am now hitting limits making me upgrade. So this is not free self hosted correct? the limits are pretty low.
