### ISSUE TITLE
Self hosting errors

### ISSUE THREAD

**Issue by kaaancan** [lunary-ai/lunary#140]
Hey guys,

the script init.sql has an issue because the line:
`alter table dataset add column format varchar default 'chat' not null;`

Will cause an error since the part which creates the table already has that columns.

Also the .env.example is wrong it should be DATABASE_URL instead of POSTGRES_URI

Also on another personal note:

I feel like its deliberately made hard to self deploy lunary.ai, and I needed to jump through some hoops to containerize it.

**Comment by hughcrt** [comment]
Hi @kaaancan ,

Thanks for reporting those issues, I've just fixed them. 

Hear you on the challenges running lunary on your own, we're aware of that. We're a small team that's had competing priorities, but we're putting more focus now on smoothing out that process, including better docs.
I hope you'll understand.

Please let us know if you run into anything else!
