### ISSUE TITLE
Feature: Adding tags via langchain calls

### ISSUE THREAD

**Issue by kaaancan** [lunary-ai/lunary#195]
Hey folks,

this is more of an feature request or maybe this is even possible. Is there a way we could tag the LCEL with a tag that gets detected by lunary. I have an AI App with a lot of llm calls from different workflows and debugging them is a little bit difficult.

**Comment by hughcrt** [comment]
Hi, are you using python?

**Comment by hughcrt** [comment]
If yes, you can use `with lunary.tags(["tag1", ["tag2"]):`. 
More details at the bottom of this page: https://lunary.ai/docs/features/tags

**Comment by kaaancan** [comment]
Nope i am using langchain-ts, would that also be possible there ?

**Comment by hughcrt** [comment]
You can do pass tags like this:

```typescript
import { ChatOpenAI } from "@langchain/openai";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { StringOutputParser } from "@langchain/core/output_parsers";
import { LunaryHandler } from "lunary/langchain";

const handler = new LunaryHandler();

const prompt = ChatPromptTemplate.fromMessages([
  ["human", "Tell me a short joke about {topic}"],
]);
const model = new ChatOpenAI({});
const outputParser = new StringOutputParser();

const chain = prompt.pipe(model).pipe(outputParser);

const response = await chain.invoke(
  {
    topic: "ice cream",
  },
  {
    callbacks: [handler],
    tags: ["tag1", "tag2"],
  }
);
console.log(response);

```
