### ISSUE TITLE
Self hosted: High db usage while idle 

### ISSUE THREAD

**Issue by kaaancan** [lunary-ai/lunary#213]
Hey folks,

hope you guys are doing well. I deployed the application via a railway template and see a high databse memory usage.

Right now the database grows around 200 to 400MB a day due to my usage with OpenAI. 

I see that there is some sort of cron job regarding reporting which may poll the database and keep a lot of the records in memory. 

Two questions:
1. Any Database settings that might help with that
2. Could we maybe add a feature flag to disable reporting

**Comment by hughcrt** [comment]
Hi,
The cron jobs are only to refresh materialized view, and should not impact RAM usage. I'm not sure what you are referring to by "reporting". Could you please give me more details?

**Comment by kaaancan** [comment]
Hey, please ignore with reporting. I think i have misread the logs.

Right now i have a database with 6.6GBs of data, 95% of this are for the runs table. My basic postgresql setup keeps almost all the 5gb in memory. Restarting the database fixes the issue and it drops down to 660MB.

I am trying to understand if there is any database setting i need to be aware of which you guys are using. This seems very unusual

**Comment by hughcrt** [comment]
It's hard for us to help without knowing more about your infrastructure.
Could you please contact us on the chat on the bottom right at https://lunary.ai, or send me email at hugh@lunary.ai?
