### ISSUE TITLE
Tags not displaying in tools traces

### ISSUE THREAD

**Issue by BespalovSergey** [lunary-ai/lunary#278]
Hello. 
Tell me, the tags are not displayed in the tool trace. Is this how it works, or is there a bug in my code?
git repo: https://github.com/ShoggothAI/motleycrew/tree/cached_calls_lunary

![image](https://github.com/lunary-ai/lunary/assets/50576059/e23f5dac-107e-46a8-b4a9-50515173fd5d)
![image](https://github.com/lunary-ai/lunary/assets/50576059/74cc868d-f043-43e4-b5dc-d78131c5d19f)

adding tags: [motleycrew/tracking/callbacks.py](https://github.com/ShoggothAI/motleycrew/blob/cached_calls_lunary/motleycrew/tracking/callbacks.py#L39)

**Comment by hughcrt** [comment]
Hi @BespalovSergey,
Could you please send me a sample of the code you're using to make this trace?

**Comment by BespalovSergey** [comment]
The code that adds the trace: https://github.com/ShoggothAI/motleycrew/blob/cached_calls_lunary/motleycrew/tracking/callbacks.py
A tag is added to this line:  https://github.com/ShoggothAI/motleycrew/blob/cached_calls_lunary/motleycrew/tracking/callbacks.py#L39

**Comment by hughcrt** [comment]
Actually, it was a problem on our end because we were displaying tags only for LLM calls. It's been fixed in the latest version 🙂
