### ISSUE TITLE
Add OpenTelemetry support

### ISSUE THREAD

**Issue by ThomasVitale** [lunary-ai/lunary#384]
I've just learned about Lunary, really great project, congratulations!

I was wondering if you envision support for OpenTelemetry in the future for data ingestion into Lunary (and perhaps https://opentelemetry.io/docs/specs/semconv/gen-ai/)?

**Comment by hughcrt** [comment]
Could you please tell me more about your use case though?

**Comment by ThomasVitale** [comment]
@hughcrt thanks for the quick reply. I'm currently researching LLM observability solutions for polyglot scenarios that include also Java and Go where OpenTelemetry is already used for standard application observability, so I was curious about possible integrations with Lunary.

**Comment by hughcrt** [comment]
The Lunary Java client should be coming this summer though!
