### ISSUE TITLE
Docker compose support

### ISSUE THREAD

**Issue by gyliu513** [lunary-ai/lunary#39]
Instead of hosted version or self-hosted version, can I run it on local host. Seems not support this option yet, any plan to support this pattern? Thanks

**Comment by hughcrt** [comment]
Hi @gyliu513,
We're definitively plan to support this option, but we have high priority bugs to fix first.
Would a docker compose work for you?

**Comment by gyliu513** [comment]
> Would a docker compose work for you?

Yes, that works, thanks @hughcrt !

**Comment by uhlhosting** [comment]
@hughcrt hi, how is the process of getting an official docker image?

**Comment by hughcrt** [comment]
Hi @uhlhosting, we've been quite busy recently, but we haven't forgotten about it. We'll update you as soon as it's ready 🙂

**Comment by hughcrt** [comment]
Hi, @uhlhosting @gyliu513, you can find our pricing for docker compose support: https://lunary.ai/pricing/self-hosted
We've had several companies using that and they're really happy about it. We still allow local deployment for free.

Please let me know if you need assistance to set up a dev environment.

**Comment by uhlhosting** [comment]
@hughcrt sorry excuse me? Prices for docker compose support, is this a joke, or it's 1st of april?
