### ISSUE TITLE
Can't signp up for lunary.ai 

### ISSUE THREAD

**Issue by luigimorel** [lunary-ai/lunary#625]
Hi @hughcrt, 

I get a CORS error on the second step of signing up 

![image](https://github.com/user-attachments/assets/7a6aae17-b41e-4d93-bb56-5a93c3e4077c)

![image](https://github.com/user-attachments/assets/fe6157d6-8f50-4c41-ad45-aa16fc5390e1)

**Comment by hughcrt** [comment]
Hi @luigimorel,
I just fixed it, there was a bug with Sentry that was fixed in a recent released, which caused the redirect on signup to not work.
Your account should have been created though, so you can log in with the credentials you've used during the signup flow.
