### ISSUE TITLE
Version mismatch causing security scanning to flag.

### ISSUE THREAD

**Issue by chinyixiang** [lunary-ai/lunary#653]
npm version is only up to v0.7.13. When trying to install latest version from github, security scanning will detect v1.0.0 from package.json and flag it as outdated version. Possible to update the package.json to match the release version?

**Comment by hughcrt** [comment]
Hi, this repo is not the npm package one. We've opened a PR to Github to fix that: https://github.com/github/advisory-database/pull/5009#issuecomment-2480079997

**Comment by vincelwt** [comment]
FYI this was merged into Github's advisory database (above PR) so shouldn't be an issue anymore
