### ISSUE TITLE
ChatBedrock & ChatGoogleVertexAI, models not showing

### ISSUE THREAD

**Issue by ninjamaster1337** [lunary-ai/lunary#77]
Currently when running the ChatBedrock or ChatGoogleVertexAI via langchainjs, the model is not showing up and no costs are calculated. It only shows the model as ChatBedrock and ChatGoogleVertexAI.

Note: this is on the cloud hosted version

**Comment by vincelwt** [comment]
Thanks for opening an issue - we'll look at this asap
